disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - class_delegate_protocol
opt_in_rules: # some rules are only opt-in
included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  
line_length: 200

identifier_name:
  min_length: 1 # only min_length
  excluded: # excluded via string array
    - access_token
